Repository AgniechaP/synthetic_data_generation, pull requests merged in 2024-03, with the labels that each got.

#6 AGPD-3 - COCO annotation system added.
  utilities/coco_parser.py
Labels: enhancement

#10 Agpd 3 pipeline combined
  README.md
  main.py
  utilities/coco_parser.py
  utilities/pipeline_steps.py
Labels: enhancement

#12 Scripts in tools folder, fix bbox in COCO
  main.py
  tools/README.md
  tools/json_to_yolo_fromat_converter.py
  tools/visualize_bbox_from_coco.py
  tools/visualize_mask_and_bbox_from_yolo.py
  utilities/coco_parser.py
Labels: bug, enhancement

#13 AGPD-8 - TQDM progressbar added.
  main.py
  requirements.txt
Labels: enhancement

#11 AGPD-4 - README of pipeline updated.
  README.md
  docs/Pipeline_architecture.svg
  docs/Pipeline_diagram.png
Labels: documentation
